#!/bin/bash
sqlite3 "${VRS_CONFIG_DIR}"/db/BaseStation.sqb 1>/dev/null <<EOF
PRAGMA locking_mode=EXCLUSIVE;
PRAGMA busy_timeout=50000;
.mode csv
.import ${VRS_CONFIG_DIR}/db/${FULLAIRCRAFT_NAME} FullAircraft
CREATE UNIQUE INDEX "Code" ON "FullAircraft" ("ModeS"    ASC);

UPDATE Aircraft
SET (FirstCreated, LastModified, ModeS, ModeSCountry, Registration, Status, Manufacturer, ICAOTypeCode, Type, SerialNo, 
RegisteredOwners, UserNotes, Interested, UserBool1, UserString1, UserString4, UserString5, UserInt1, UserInt3, OperatorFlagCode) = 
(SELECT FullAircraft.FirstCreated, FullAircraft.LastModified, FullAircraft.ModeS, FullAircraft.ModeSCountry, FullAircraft.Registration,  FullAircraft.Status, FullAircraft.Manufacturer, 
FullAircraft.ICAOTypeCode, FullAircraft.Type, FullAircraft.SerialNo, FullAircraft.RegisteredOwners, FullAircraft.UserNotes, FullAircraft.Interested, FullAircraft.UserBool1,
FullAircraft.UserString1, FullAircraft.UserString4, FullAircraft.UserString5, FullAircraft.UserInt1, FullAircraft.UserInt3, FullAircraft.OperatorFlagCode 
FROM FullAircraft WHERE FullAircraft.ModeS = Aircraft.ModeS)
WHERE EXISTS (SELECT * FROM FullAircraft WHERE FullAircraft.ModeS = Aircraft.ModeS);


INSERT INTO Aircraft (FirstCreated, LastModified, ModeS, ModeSCountry, Country, Registration, Status, Manufacturer, ICAOTypeCode, Type, SerialNo, 
                        RegisteredOwners, UserNotes, Interested, UserBool1, UserString1, UserString4, UserString5, UserInt1, UserInt3, OperatorFlagCode)
SELECT FirstCreated, LastModified, ModeS, ModeSCountry, Country, Registration, Status, Manufacturer, ICAOTypeCode, Type, SerialNo, 
                        RegisteredOwners, UserNotes, Interested, UserBool1, UserString1, UserString4, UserString5, UserInt1, UserInt3, OperatorFlagCode
FROM FullAircraft
WHERE NOT EXISTS (SELECT * FROM Aircraft WHERE FullAircraft.ModeS = Aircraft.ModeS);

DROP TABLE FullAircraft;
VACUUM;
EOF
